server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Compression gzip
    gzip on;
    gzip_types text/plain text/css application/javascript application/json image/svg+xml;
    gzip_min_length 1024;

    # Cache assets statiques Next.js (_next/static = immutable)
    location /_next/static/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # Pages avec trailing slash (next export)
    location / {
        try_files $uri $uri/ $uri.html $uri/index.html =404;
    }

    # 404 custom
    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}
